[package]
name = "numerical_testing"
version = "0.1.0"
authors = ["Chris Prohoda <cgprohoda@gmail.com>"]
edition = "2021"

[dependencies]
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
plotters = "0.3.5"
